# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

target 'iOS-Jenkins' do
  # Comment the next line if you're not using Swift and don't want to use dynamic frameworks
  use_frameworks!

  # Pods for iOS-Jenkins

  target 'iOS-JenkinsTests' do
    inherit! :search_paths
    # Pods for testing
  end

  target 'iOS-JenkinsUITests' do
    inherit! :search_paths
    # Pods for testing
  end

end
